### ISSUE TITLE
Проверка ЛР2

### ISSUE THREAD

**Issue by DSG888** [DSG888/SibSUTIS#1]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
Топология репозитория на момент сдачи:

```
*   bc04398 (origin/master, origin/HEAD, master) Произведен мерж-коммит (...)
|\  
| * e027956 (HEAD, origin/future) В отдельной ветке (...)
* | 3145e74 Изменена функция main.
|/  
* ae40147 ЛР2
```
  Реализация функционала раскидана по двум веткам, мерж выполнен без ребейза. Исправить можно следующим образом:
  1. Переключиться на ветку `future` (`git checkout`).
  1. Добавить в нее уже существующий коммит `3145e74` (`git cherry-pick`).
  1. Вернуть ветку `master` на первый коммит (`git reset`).
  1. Выполнить мерж.
  1. Выполнить пуш ветки `master` с опцией `--force`.

Все это можно сделать без пересоздания репозитория.

Сообщения некоторых коммитов сейчас бросились в другую крайность. Если посмотреть на заголовок https://github.com/DSG888/SibSUTIS/commit/e027956fca5155d0c361bb54337bc0d602b139e5, то можно увидеть, что он обрезается гитхабом. Нет необходимости писать в заголовке, что коммит выполнен в отдельной ветке. Это видно из топологии.

Также на паре мы обсуждали, что для переписывания истории не обязательно пересоздавать репозиторий, можно использовать команду `git rebase` с опцией `--interactive`.

**Comment by DSG888** [comment]
Выполнено.

**Comment by evgeny-p** [comment]
1. Был пропущен пункт с возвратом мастера на первый коммит, история стала выглядеть еще сложнее. Исправить все еще можно, но теперь требуется гораздо больше действий. Необходимые команды и документация Вам известны.

1. При выполнении операции `cherry-pick` в заголовок коммита было скопировано сообщение из списка замечаний. Нарушено требование на соответствие сообщений коммитов их содержанию. В предыдущем комментарии уже было аналогичное замечание.

1. Не был разрешен конфликт в коммите https://github.com/DSG888/SibSUTIS/commit/297ebf27125fa41344553f3a089cd9ec7723dd55.

**Comment by DSG888** [comment]
git reset был выполнен после возврата в ветку master (git checkout master).
Эта команда не вызвала ошибок.

**Comment by evgeny-p** [comment]
Если Вы просто скопировали команду `git reset`, то вполне ожидаемо, что не получили нужного эффекта. Цель состояла в том, чтобы перенести указатель `master` на первый коммит. Ожидаемый сценарий:

1. Ок, выполняем `git reset`.
1. Обращам внимание на то, что `master` не был перенесен на первый коммит, и исправлению ситуации это не поспособствует.
1. Читаем `man git-reset`, обращаем внимание, что для переноса ветки нужно указать ссылку на коммит. Видим, что есть несколько режимов: `--hard`, `--soft` и `--mixed`, разбираемся в чем отличие и какой режим нужен для конкретной задачи.

Из текущей ситуации наиболее простым выходом кажется следующий:

1. На текущем положении мастера поставить тег. Только локально, чтобы не потерять историю в процессе ее переписывания.
1. Вернуть мастер на самый первый коммит. Серией черри-пиков коммитов восстановить историю, соблюдая все требования.

**Comment by DSG888** [comment]
.

**Comment by DSG888** [comment]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
Принято.
