### ISSUE TITLE
ЛР5

### ISSUE THREAD

**Issue by DSG888** [DSG888/SibSUTIS#2]
Уточните задачу по ЛР5.

Что необходимо проверить в тестах?

To: @evgeny-p

**Comment by evgeny-p** [comment]
В Вашем случае в вычислительной функции есть 6 точек выхода (не считая заглушки). Все ветки кода должны быть покрыты тестами. Т.е. нужно подготовить по одному набору тестовых данных на каждую ветку кода. В каждом тесте (в секции Then) необходимо проверить корректность возвращаемого значения и корректность значений найденных корней, если они есть.

Обращаю внимание на то, что unit-тестирование предполагает покрытие тестами именно функции и проверку результирующих данных, а не запуск приложения с последующей проверкой текстового представления результатов.

**Comment by DSG888** [comment]
В реализации можно использовать assert.h вместо ctest?

**Comment by evgeny-p** [comment]
У макроса `assert` другое назначение: диагностика приложения в отладочной сборке.

Конструкции библиотек, предназначенных для unit-тестирования, отмечают статус прохождения тестов, что способствует формированию человекопонятного отчета. Также в случае использования `assert` выполнение тестов завершится при падении первого же теста. В случае использования библиотек будут запущены все тесты, результирующий отчет будет полным.

Я не настаиваю на использовании именно ctest. Библиотека была выбрана исходя из следующих требований:

1. В случае непрохождения тестов приложение должно завершаться с ненулевым кодом.
1. Легкость установки и компиляции. Данная библиотека состоит из единсвенного заголовочного файла и не требует внешних зависимостей.

**Comment by DSG888** [comment]
Библиотека так же содержит лицензию (Apache License) накладывающую огранияения на распространение.

**Comment by evgeny-p** [comment]
Не вижу никаких ограничений, мешающих использовать библиотеку и выполнить задание.

А Вы сейчас уводите обсуждение от основного предмета.

**Comment by DSG888** [comment]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Слишком много изменений в одном коммите. Если уж дублируете код предыдущей работы, делайте импорт отдельным коммитом, а новые изменения, относящиеся непосредственно к текущей работе — отдельным. Начать разделение коммита на два можно с команды `git reset --mixed origin/master`, находясь на ветке `LR5`.

1. Циклические зависимости в мейкфайле.

1. Многократный запуск `make` приводит к пересборке проекта при отсутствии в нем изменений.

1. В тестах проверяется, что при отсутствии решений значения `x1` и `x2` равны нулю, при этом функция не дает таких гарантий.

1. Не покрыты тестами следующие ветки кода (указаны строки в файле `calc.c`):
  1. Строка 26, уравнение `c = 0`.
  1. Строка 30, уравнение `bx + c = 0`.
  1. Строка 55, заглушка.

1. В мейкфайле не придусмотрена цель для запуска тестов.

1. В файле `mytests.c` Вам пришлось определить макросы, соответствующие кодам возврата вычислительной функции. При изменении этих кодов возникает необходимость поддерживать два списка таких макросов. Поскольку они являются частью интерфейса функции, имеет смысл вынести их в заголовочный файл и использовать одни и те же определения.

1. Не нужно инклудить файлы `*.c`.

1. Компилировать нужно с опцией `-Wall`. Приложение должно компилироваться без предупреждений.

1. Неконсистентное именование сущностей в тестах: используются CamelCase, lowerCamelCase, UPPERCASE, MIXED_underscore. Определитесь с соглашениями.

**Comment by DSG888** [comment]
Работу выполнил Дорогин Сергей

(Пока без слияния, так как не проверена ЛР4. Смотреть ветку LR5)

4: В тестах проверяется значения x1, x2 и возвращаемое значение NO_ROOT (0).
6: По заданию не требуется прИдусматривать цель для запуска тестов. Это ЛР5, а не ЛР6.
To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Приложение не компилируется.
1. Не покрыт тестами случай a = 0, b = 0, c != 0.
1. Не покрыта тестами «заглушка». Хинт: если в функции есть недостижимый код, то ее нужно переписать так, чтобы его не было. Требование на компиляцию без ошибок и предупреждений сохраняется.
1. > В тестах проверяется значения x1, x2 и возвращаемое значение NO_ROOT (0)

  Если возвращаемое значение говорит о том, что корней нет, то какой смысл проверять их значения? Спецификация функции явно говорит о том, какие значения принимают корни в случае их отсутствия?
1. > Это ЛР5, а не ЛР6.

  На занятии говорили о необходимости автоматизации запуска тестов. Предоставление интерфейса для запуска — шаг к автоматизации.

По части использования гита Вы повторяете ошибки прошлых работ.

1. Смотрим на коммит https://github.com/DSG888/SibSUTIS/commit/7979060f9e7eec8b3dd4ca7e69a02eb0e368d2c2. 
  Заголовок: «Убраны циклические зависимости из makefile».
  Дифф содержит три изменения:
  1. Добавлен `.gitignore`
  1. Реализован Makefile
  1. Разработан скрипт для интеграционного тестирования.

  Выбранный Вами заголовок был бы уместен, если бы коммит содержал патч, исправляющий существующий мейкфайл.

1. В коммите https://github.com/DSG888/SibSUTIS/commit/06b32aacaffb606305569b230a7a076b6b5162a3 несколько независимых изменений.

PS
Почему в одном из коммитов слово «библиотека» применительно к ctest взято в кавычки?

**Comment by DSG888** [comment]
"3. Не покрыта тестами «заглушка». Хинт: если в функции есть недостижимый код, то ее нужно переписать так, чтобы его не было."
	Это фрагмент теста. Если было возвращено значение -1, значит программист допустил ошибку. (Иначе зачем эти тесты?)

Я привык называть библиотеками файлы *.so и *.a. 


Работу выполнил Дорогин Сергей
To: @evgeny-p

**Comment by evgeny-p** [comment]
> Это фрагмент теста.

Прежде всего, это часть интерфейса функции, не относящаяся к предметной области, а также недостижимый код. В функцию возможно внести коррективы, не ухудшив покрытие тестами, но устранив недостижимый код.

**Comment by DSG888** [comment]
Заглушка убрана!
To: @evgeny-p

**Comment by evgeny-p** [comment]
Грубая работа. Теперь код компилируется с предупреждениями.

**Comment by DSG888** [comment]
Исправлено.

**Comment by evgeny-p** [comment]
Принято.
