### ISSUE TITLE
Проверка ЛР4

### ISSUE THREAD

**Issue by DSG888** [DSG888/SibSUTIS#3]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Приложение не компилируется.

1. Нарушение рабочего процесса: один из коммитов, относящихся к задаче, выполнен в мастере, второй — в ветке. Аналогичное замечание было по ЛР2.

1. > Создано многофайловое приложение

  Недостаточно конкретно описывает содержание коммита. Одна из возможных формулировок: «Функция решения квадратного уравнения вынесена в отдельный файл».

**Comment by DSG888** [comment]
"Приложение не компилируется."
исправлено.

**Comment by DSG888** [comment]
Работу выполнил Дорогин Сергей

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Мейкфайл содержит циклические зависимости, см. вывод команды `make`.
2. Не совсем ясно, зачем нужно было копировать исходники второй лабы, когда можно было выполнять четвертое задание на основе второго. Сейчас же получился один огромный коммит с импортом всей работы. В рамках данной работы этот пункт можно не исправлять, но в будущем старайтесь включать в коммит минимальные самодостаточные порции изменений.

**Comment by DSG888** [comment]
Убраны циклические зависимости из makefile

**Comment by evgeny-p** [comment]
Принято.
